// meal_data.js
// 建議將此檔案儲存為 meal_data.js 並與主 HTML 檔案和 restaurant_data.js 放在同一目錄下

const mealData = {
    breakfast: {
        "港式": [
            { name: "沙嗲牛肉麵配炒蛋多士", moods: ["Comfort Food", "快靚正"] },
            { name: "雪菜肉絲米粉", moods: ["快靚正", "健康清淡啲～"] },
            { name: "腿蛋治", moods: ["快靚正"] },
            { name: "火腿通粉", moods: ["快靚正", "Comfort Food"] },
            { name: "皮蛋瘦肉粥配炒麵", moods: ["Comfort Food", "健康清淡啲～"] },
            { name: "腸粉", moods: ["快靚正", "Comfort Food"] },
            { name: "鮮油菠蘿包", moods: ["Comfort Food"] },
            { name: "餐蛋麵", moods: ["快靚正", "Comfort Food"] },
            { name: "即叫即製粢飯", moods: ["Comfort Food"] },
            { name: "魚柳包", moods: ["快靚正"] },
            { name: "豬扒包", moods: ["Comfort Food"] },
            { name: "雞批", moods: ["Comfort Food"] },
            { name: "腿蓉奄列", moods: ["Comfort Food", "健康清淡啲～"] },
            { name: "鮮茄牛肉通粉", moods: ["Comfort Food", "健康清淡啲～"] },
            { name: "炸菜肉絲公仔麵", moods: ["快靚正", "Comfort Food"] },
            { name: "五香肉丁公仔麵", moods: ["快靓正", "Comfort Food"] },
            { name: "鮑魚雞粥早餐", moods: ["想食豪啲！", "Comfort Food"] } // 新增或調整
        ],
        "西式": [
            { name: "穀物片配鮮奶", moods: ["健康清淡啲～", "快靚正"] }, // 調整
            { name: "乳酪杯配水果麥片", moods: ["健康清淡啲～"] },
            { name: "煙肉蛋奄列配薯餅", moods: ["Comfort Food"] },
            { name: "英式鬆餅 (Scones) 配果醬忌廉", moods: ["想食豪啲！", "Comfort Food"] }, // 調整
            { name: "美式鬆餅 (Pancakes) 配楓糖漿", moods: ["Comfort Food"] }, // 調整
            { name: "法式吐司 (French Toast) 配雜莓", moods: ["Comfort Food", "想食豪啲！"] }, // 調整
            { name: "牛角包配牛油果炒蛋", moods: ["快靚正", "健康清淡啲～", "Comfort Food"] }, // 調整
            { name: "英式全餐 (Full English Breakfast)", moods: ["想食豪啲！", "Comfort Food"] }, // 調整
            { name: "煙三文魚忌廉芝士貝果 (Bagel)", moods: ["健康清淡啲～", "想食豪啲！"] }, // 調整
            { name: "比利時窩夫 (Waffles) 配雪糕朱古力醬", moods: ["Comfort Food", "想食豪啲！"] }, // 調整
            { name: "煙三文魚炒蛋配酸種麵包", moods: ["想食豪啲！", "健康清淡啲～"] }, // 調整
            { name: "芝士火腿可頌 (Croissant)", moods: ["Comfort Food", "快靚正"] },
            { name: "牛油果多士配水煮蛋", moods: ["健康清淡啲～"] }, // 調整
            { name: "炒雜菌黑松露多士", moods: ["健康清淡啲～", "想食豪啲！", "Comfort Food"] } // 調整
        ],
        "中式": [
            { name: "蝦餃燒賣拼盤", moods: ["Comfort Food", "想食豪啲！"] }, // 調整
            { name: "糯米雞", moods: ["Comfort Food"] },
            { name: "山竹牛肉球", moods: ["Comfort Food"] }, // 調整
            { name: "菜肉包", moods: ["快靚正"] },
            { name: "潮州粉粿", moods: ["Comfort Food"] }, // 調整
            { name: "上海粢飯糰", moods: ["Comfort Food", "快靓正"] },
            { name: "瑤柱白粥配油炸鬼", moods: ["健康清淡啲～", "Comfort Food", "想食豪啲！"] }, // 調整
            { name: "煎堆油炸鬼", moods: ["Comfort Food"] },
            { name: "饅頭夾煎蛋", moods: ["健康清淡啲～", "快靚正"] }, // 調整
            { name: "鹹豆漿加料版", moods: ["Comfort Food", "健康清淡啲～"] }, // 調整
            { name: "生煎包", moods: ["Comfort Food"] },
            { name: "小籠包", moods: ["Comfort Food", "想食豪啲！"] },
            { name: "窩貼", moods: ["Comfort Food", "快靚正"] },
            { name: "韮菜盒", moods: ["Comfort Food"] }
        ],
        "台式": [
            { name: "台式古早味大飯糰", moods: ["Comfort Food", "快靚正"] }, // 調整
            { name: "芝士肉鬆蛋餅", moods: ["快靚正", "Comfort Food"] }, // 調整
            { name: "台式鹹豆漿配油條", moods: ["Comfort Food", "健康清淡啲～"] }, // 調整
            { name: "豪華總匯三文治", moods: ["快靚正", "Comfort Food", "想食豪啲！"] }, // 調整
            { name: "台式刈包 (爌肉)", moods: ["Comfort Food", "想食豪啲！"] }, // 調整
            { name: "香煎蘿蔔糕 (台式)", moods: ["Comfort Food"] }, // 調整
            { name: "燒餅油條夾蛋", moods: ["Comfort Food", "快靚正"] }, // 調整
            { name: "蔥油餅加蛋", moods: ["Comfort Food", "快靚正"] }, // 調整
            { name: "蔬菜鮪魚蛋餅", moods: ["健康清淡啲～", "快靚正"] } // 新增
        ],
        "其他": [
            { name: "豪華水果拼盤配乳酪", moods: ["健康清淡啲～", "想食豪啲！"] }, // 調整
            { name: "能量棒配黑咖啡", moods: ["快靚正", "健康清淡啲～"] }, // 調整
            { name: "便利店御飯糰配豆漿", moods: ["快靚正"] }, // 調整
            { name: "即食燕麥片配堅果", moods: ["健康清淡啲～", "快靚正"] }, // 調整
            { name: "隔夜燕麥杯 (Overnight Oats)", moods: ["健康清淡啲～"] }, // 調整
            { name: "益生菌乳酪飲品", moods: ["健康清淡啲～", "快靚正"] }, // 調整
            { name: "雞蛋仔 (原味)", moods: ["快靚正", "Comfort Food"] }, // 調整
            { name: "藜麥沙律杯", moods: ["健康清淡啲～"] }, // 調整
            { name: "希臘乳酪配蜜糖堅果水果", moods: ["健康清淡啲～", "想食豪啲！", "Comfort Food"] }, // 調整
            { name: "自家製能量球 (Energy Balls)", moods: ["健康清淡啲～", "快靚正"] }, // 調整
            { name: "暖心蜂蜜薑茶", moods: ["Comfort Food", "健康清淡啲～"] } // 新增
        ]
    },
    lunch: {
        "港式": [ { name: "碟頭飯 (例：粟米肉粒飯)", moods: ["快靚正", "Comfort Food"] }, { name: "焗豬扒飯", moods: ["Comfort Food", "想食豪啲！"] }, { name: "乾炒牛河", moods: ["Comfort Food"] }, { name: "車仔麵", moods: ["快靚正"] }, { name: "燒味飯 (例：叉燒飯)", moods: ["快靚正", "Comfort Food"] }, { name: "雲吞麵/牛腩河", moods: ["Comfort Food", "健康清淡啲～"] }, { name: "常餐", moods: ["快靚正", "Comfort Food"] }, { name: "炒粉麵 (例：星洲炒米)", moods: ["快靚正"] }, { name: "豆腐火腩飯", moods: ["Comfort Food"] }, { name: "枝竹火腩飯", moods: ["Comfort Food"] }, { name: "鮮茄焗豬扒飯", moods: ["Comfort Food", "想食豪啲！"] }, { name: "瑞士雞翼撈公仔麵", moods: ["Comfort Food"] }, { name: "XO醬海鮮炒飯", moods: ["想食豪啲！"] }, { name: "滑蛋蝦仁飯", moods: ["Comfort Food", "健康清淡啲～"] }, { name: "福建炒飯", moods: ["Comfort Food"] }, { name: "魚湯米線", moods: ["健康清淡啲～", "快靚正"] } ],
        "中式": [ { name: "點心 (例：蝦餃燒賣)", moods: ["Comfort Food", "想食豪啲！"] }, { name: "兩餸飯", moods: ["快靚正"] }, { name: "蒸飯套餐 (例：北菇蒸雞飯)", moods: ["健康清淡啲～", "快靚正"] }, { name: "湯飯/泡飯", moods: ["健康清淡啲～", "Comfort Food"] }, { name: "麻婆豆腐飯", moods: ["Comfort Food"] }, { name: "水煮牛肉飯", moods: ["Comfort Food"] }, { name: "擔擔麵", moods: ["Comfort Food"] }, { name: "酸辣粉", moods: ["Comfort Food"] }, { name: "蘭州拉麵", moods: ["Comfort Food"] }, { name: "餃子 (水餃/煎餃)", moods: ["快靚正", "Comfort Food"] }, { name: "麻辣燙", moods: ["Comfort Food"] }, { name: "酸菜魚米線", moods: ["Comfort Food", "想食豪啲！"] }, { name: "上海排骨菜飯", moods: ["Comfort Food"] }, { name: "北京炸醬麵", moods: ["Comfort Food"] }, { name: "揚州炒飯", moods: ["Comfort Food", "快靚正"] }, { name: "清炒時蔬配白飯", moods: ["健康清淡啲～"] } ],
        "台式": [ { name: "滷肉飯", moods: ["Comfort Food", "快靚正"] }, { name: "雞肉飯", moods: ["健康清淡啲～", "快靚正"] }, { name: "台式牛肉麵", moods: ["Comfort Food", "想食豪啲！"] }, { name: "排骨便當", moods: ["快靚正", "Comfort Food"] }, { name: "鹽酥雞便當", moods: ["Comfort Food"] }, { name: "三杯雞飯", moods: ["Comfort Food", "想食豪啲！"] }, { name: "刈包", moods: ["Comfort Food"] }, { name: "大腸麵線", moods: ["Comfort Food"] }, { name: "蚵仔煎", moods: ["Comfort Food"] }, { name: "筒仔米糕", moods: ["Comfort Food"] }, { name: "麻油雞麵線", moods: ["Comfort Food", "健康清淡啲～"] }, { name: "肉羹湯/飯/麵", moods: ["Comfort Food"] } ],
        "日式": [ { name: "壽司拼盤", moods: ["想食豪啲！", "健康清淡啲～"] }, { name: "刺身飯", moods: ["想食豪啲！", "健康清淡啲～"] }, { name: "豬扒丼", moods: ["Comfort Food"] }, { name: "親子丼", moods: ["Comfort Food", "健康清淡啲～"] }, { name: "牛肉飯 (牛丼)", moods: ["快靚正", "Comfort Food"] }, { name: "拉麵 (豚骨/醬油/味噌)", moods: ["Comfort Food"] }, { name: "烏冬 (湯烏冬/炒烏冬)", moods: ["Comfort Food", "健康清淡啲～"] }, { name: "日式咖喱飯", moods: ["Comfort Food", "快靚正"] }, { name: "天婦羅丼", moods: ["想食豪啲！"] }, { name: "蕎麥麵/冷麵", moods: ["健康清淡啲～", "快靚正"] }, { name: "日式便當 (Bento)", moods: ["快靚正", "健康清淡啲～"] }, { name: "鰻魚飯 (輕量版)", moods: ["想食豪啲！", "Comfort Food"] }, { name: "日式漢堡扒飯", moods: ["Comfort Food"] }, { name: "滑蛋豬扒飯 (勝丼)", moods: ["Comfort Food"] }, { name: "鐵板燒午市套餐", moods: ["想食豪啲！", "快靚正"] } ],
        "韓式": [ { name: "韓式拌飯 (Bibimbap)", moods: ["健康清淡啲～"] }, { name: "泡菜炒飯", moods: ["Comfort Food", "快靚正"] }, { name: "韓式炸醬麵", moods: ["Comfort Food"] }, { name: "豆腐海鮮湯配飯", moods: ["健康清淡啲～", "Comfort Food"] }, { name: "韓式炸雞 (午市套餐)", moods: ["Comfort Food", "想食豪啲！"] }, { name: "部隊鍋 (一人份)", moods: ["Comfort Food"] }, { name: "紫菜包飯 (Kimbap)", moods: ["快靚正", "健康清淡啲～"] }, { name: "人參雞湯 (輕量版)", moods: ["健康清淡啲～", "Comfort Food", "想食豪啲！"] }, { name: "韓式炒粉絲 (Japchae)", moods: ["健康清淡啲～"] }, { name: "辣炒年糕 (Tteokbokki)", moods: ["Comfort Food"] }, { name: "韓式冷麵 (Naengmyeon)", moods: ["健康清淡啲～"] }, { name: "石頭鍋飯 (Dolsot Bibimbap)", moods: ["Comfort Food"] }, { name: "韓式豬肉蓋飯 (Jeyuk Deopbap)", moods: ["Comfort Food", "快靚正"] } ],
        "西式": [ { name: "意粉 (肉醬/白汁/香草)", moods: ["Comfort Food", "快靚正"] }, { name: "薄餅 (Pizza) 單人份", moods: ["Comfort Food", "想食豪啲！", "快靚正"] }, { name: "公司三文治配薯條", moods: ["快靚正", "Comfort Food"] }, { name: "西式沙律配雞扒/三文魚", moods: ["健康清淡啲～"] }, { name: "漢堡包餐", moods: ["快靚正", "Comfort Food"] }, { name: "焗薯配料", moods: ["Comfort Food"] }, { name: "西式湯配麵包", moods: ["健康清淡啲～", "快靚正"] }, { name: "烤雞/雞扒餐", moods: ["Comfort Food", "想食豪啲！"] }, { name: "魚柳包配薯條", moods: ["快靚正"] }, { name: "意式肉丸意粉", moods: ["Comfort Food"] }, { name: "卡邦尼意粉", moods: ["Comfort Food", "想食豪啲！"] }, { name: "烤三文魚配雜菜", moods: ["健康清淡啲～", "想食豪啲！"] }, { name: "肉醬千層麵", moods: ["Comfort Food", "想食豪啲！"] } ],
        "東南亞": [ { name: "泰式豬頸肉飯", moods: ["Comfort Food", "快靓正"] }, { name: "青咖喱雞飯", moods: ["Comfort Food"] }, { name: "冬蔭功金邊粉", moods: ["Comfort Food", "想食豪啲！"] }, { name: "海南雞飯", moods: ["Comfort Food", "健康清淡啲～"] }, { name: "越南生牛肉河 (Pho)", moods: ["健康清淡啲～", "Comfort Food"] }, { name: "扎肉撈檬", moods: ["健康清淡啲～", "快靚正"] }, { name: "喇沙 (Laksa)", moods: ["Comfort Food", "想食豪啲！"] }, { name: "肉骨茶配白飯", moods: ["Comfort Food", "健康清淡啲～"] }, { name: "泰式炒河 (Pad See Ew)", moods: ["Comfort Food"] }, { name: "印尼炒飯 (Nasi Goreng)", moods: ["Comfort Food"] }, { name: "泰式船麵", moods: ["Comfort Food"] }, { name: "越南法式三文治 (Banh Mi)", moods: ["快靚正"] }, { name: "星洲炒蘿蔔糕", moods: ["Comfort Food"] }, { name: "泰式菠蘿炒飯", moods: ["Comfort Food", "想食豪啲！"] }, { name: "馬來西亞椰漿飯 (Nasi Lemak)", moods: ["Comfort Food"] } ],
        "快餐/輕食": [ { name: "連鎖快餐套餐", moods: ["快靚正"] }, { name: "Subway潛艇堡", moods: ["快靚正", "健康清淡啲～"] }, { name: "便利店飯盒/意粉", moods: ["快靚正"] }, { name: "沙律杯", moods: ["健康清淡啲～", "快靚正"] }, { name: "杯麵", moods: ["快靚正", "Comfort Food"] }, { name: "烤雞卷餅 (Wrap)", moods: ["快靚正", "健康清淡啲～"] }, { name: "意式薄餅 (單片)", moods: ["快靚正"] }, { name: "熱狗", moods: ["快靚正", "Comfort Food"] }, { name: "墨西哥夾餅 (Quesadilla)", moods: ["快靚正", "Comfort Food"] }, { name: "即食湯包配麵包", moods: ["快靚正", "健康清淡啲～"] }, { name: "豪華版公司三文治", moods: ["想食豪啲！", "Comfort Food"] } ],
        "其他": [ { name: "印度咖喱配薄餅 (Naan)", moods: ["Comfort Food", "想食豪啲！"] }, { name: "土耳其烤肉卷 (Kebab)", moods: ["快靚正", "Comfort Food"] }, { name: "墨西哥卷餅 (Burrito)", moods: ["Comfort Food"] }, { name: "中東旋轉烤肉 (Shawarma)", moods: ["快靚正"] }, { name: "希臘沙律配烤雞", moods: ["健康清淡啲～"] }, { name: "Poke Bowl (夏威夷魚生飯)", moods: ["健康清淡啲～", "想食豪啲！"] }, { name: "俄羅斯餃子 (Pelmeni) 配酸忌廉", moods: ["Comfort Food"] }, { name: "西班牙小食拼盤 (Tapas)", moods: ["想食豪啲！"] } ]
    },
    afternoonTea: {
        "港式": [ { name: "西多士", moods: ["Comfort Food", "想食豪啲！"] }, { name: "炸雞脾薯條", moods: ["Comfort Food"] }, { name: "奶油豬仔包", moods: ["快靚正", "Comfort Food"] }, { name: "蛋撻", moods: ["快靚正", "Comfort Food"] }, { name: "菠蘿油", moods: ["Comfort Food"] }, { name: "公司三文治", moods: ["快靚正"] }, { name: "熱狗", moods: ["快靚正"] }, { name: "沙嗲牛肉包", moods: ["Comfort Food"] }, { name: "炸魚薯條 (茶記版)", moods: ["Comfort Food"] }, { name: "豬扒包", moods: ["Comfort Food"] }, { name: "雞尾包", moods: ["Comfort Food"] }, { name: "咖喱角", moods: ["Comfort Food"] }, { name: "炸鮮奶", moods: ["Comfort Food", "想食豪啲！"] }, { name: "花生醬格仔餅", moods: ["Comfort Food", "快靚正"] }, { name: "紅豆冰", moods: ["Comfort Food"] }, { name: "楊枝甘露", moods: ["健康清淡啲～", "想食豪啲！"] } ],
        "西式": [ { name: "英式鬆餅 (Scones) 配果醬忌廉", moods: ["想食豪啲！", "Comfort Food"] }, { name: "精緻Cupcakes", moods: ["想食豪啲！"] }, { name: "法式Macarons禮盒", moods: ["想食豪啲！"] }, { name: "紐約芝士蛋糕", moods: ["Comfort Food", "想食豪啲！"] }, { name: "比利時窩夫 (Waffles) 配雪糕", moods: ["Comfort Food", "想食豪啲！"] }, { name: "手指三文治拼盤", moods: ["健康清淡啲～", "快靚正"] }, { name: "法式鹹派 (Quiche Lorraine)", moods: ["Comfort Food"] }, { name: "美式冬甩 (Donuts) 多款口味", moods: ["Comfort Food", "快靚正"] }, { name: "朱古力布朗尼 (Brownie) 配雪糕", moods: ["Comfort Food", "想食豪啲！"] }, { name: "法式檸檬撻", moods: ["想食豪啲！"] }, { name: "雜錦水果撻", moods: ["健康清淡啲～", "想食豪啲！"] }, { name: "吉士泡芙 (Cream Puff)", moods: ["Comfort Food"] }, { name: "瑪德蓮蛋糕 (Madeleine)", moods: ["想食豪啲！"] }, { name: "經典英式下午茶套餐 (三層架)", moods: ["想食豪啲！", "Comfort Food"] }, { name: "水果沙律杯", moods: ["健康清淡啲～", "快靚正"] } ],
        "日式": [ { name: "精選和菓子禮盒", moods: ["健康清淡啲～", "想食豪啲！"] }, { name: "抹茶卷蛋", moods: ["Comfort Food"] }, { name: "銅鑼燒 (Dorayaki)", moods: ["Comfort Food", "快靚正"] }, { name: "日式梳乎厘Pancake", moods: ["想食豪啲！", "Comfort Food"] }, { name: "鯛魚燒 (紅豆/吉士)", moods: ["Comfort Food", "快靚正"] }, { name: "章魚小丸子 (Takoyaki)", moods: ["快靚正", "Comfort Food"] }, { name: "日式可麗餅 (Crepe) 配水果忌廉", moods: ["Comfort Food", "想食豪啲！"] }, { name: "草莓大福 (Daifuku)", moods: ["Comfort Food"] }, { name: "流心芝士撻", moods: ["Comfort Food", "想食豪啲！"] }, { name: "日式醬油糰子 (Dango)", moods: ["Comfort Food"] }, { name: "蕨餅 (Warabimochi) 配黃豆粉黑糖", moods: ["健康清淡啲～"] } ],
        "台式": [ { name: "珍珠奶茶", moods: ["Comfort Food", "快靚正"] }, { name: "鹽酥雞 (小食)", moods: ["Comfort Food", "快靚正"] }, { name: "甜不辣", moods: ["Comfort Food", "快靚正"] }, { name: "芋圓仙草豆花", moods: ["Comfort Food", "健康清淡啲～"] }, { name: "車輪餅 (紅豆/奶油/芋泥)", moods: ["Comfort Food", "快靚正"] }, { name: "台式香腸配蒜片", moods: ["Comfort Food"] }, { name: "炸地瓜球", moods: ["Comfort Food"] }, { name: "綜合仙草凍", moods: ["健康清淡啲～", "Comfort Food"] }, { name: "檸檬愛玉冰", moods: ["健康清淡啲～"] }, { name: "鳳梨酥禮盒", moods: ["Comfort Food", "想食豪啲！"] }, { name: "太陽餅", moods: ["Comfort Food"] }, { name: "豪華水果茶", moods: ["想食豪啲！", "健康清淡啲～"] } ],
        "中式": [ { name: "點心拼盤 (春卷、鹹水角、蝦餃)", moods: ["快靚正", "Comfort Food", "想食豪啲！"] }, { name: "養生糖水 (紅豆沙、綠豆沙、芝麻糊)", moods: ["Comfort Food", "健康清淡啲～"] }, { name: "砵仔糕 (黃糖/白糖)", moods: ["快靚正", "Comfort Food"] }, { name: "艾草茶粿", moods: ["健康清淡啲～"] }, { name: "老婆餅/老公餅", moods: ["Comfort Food"] }, { name: "豆沙窩餅", moods: ["Comfort Food"] }, { name: "擂沙湯圓", moods: ["Comfort Food"] }, { name: "馬仔", moods: ["Comfort Food"] }, { name: "芝麻卷", moods: ["Comfort Food"] }, { name: "白糖糕", moods: ["Comfort Food", "健康清淡啲～"] } ],
        "快餐/輕食": [ { name: "薯條配特色醬", moods: ["快靚正", "Comfort Food"] }, { name: "蜜糖雞翼", moods: ["Comfort Food"] }, { name: "迷你薄餅 (一人份)", moods: ["快靚正", "Comfort Food"] }, { name: "雞蛋仔", moods: ["快靚正", "Comfort Food"] }, { name: "格仔餅", moods: ["快靚正", "Comfort Food"] }, { name: "魚蛋燒賣 (街頭小食)", moods: ["快靚正", "Comfort Food"] }, { name: "炸雞塊配醬", moods: ["Comfort Food", "快靚正"] }, { name: "粟米杯", moods: ["快靚正", "健康清淡啲～"] }, { name: "碗仔糕", moods: ["快靚正", "Comfort Food"] }, { name: "洋蔥圈", moods: ["Comfort Food"] }, { name: "雪糕新地", moods: ["Comfort Food", "想食豪啲！"] }, { name: "水果杯", moods: ["健康清淡啲～", "快靚正"] } ]
    },
    dinner: {
        "港式": [ { name: "鑊氣小炒 (例：咕嚕肉, 豉椒炒蜆)", moods: ["Comfort Food", "想食豪啲！"] }, { name: "海鮮餐 (例：清蒸海上鮮, 蒜蓉粉絲蒸扇貝)", moods: ["想食豪啲！"] }, { name: "潮州打冷 (例：滷水鵝片, 蠔餅)", moods: ["Comfort Food"] }, { name: "臘味煲仔飯", moods: ["Comfort Food"] }, { name: "火鍋 (打邊爐) - 海鮮或肥牛", moods: ["想食豪啲！", "Comfort Food"] }, { name: "胡椒豬肚雞煲", moods: ["想食豪啲！", "Comfort Food"] }, { name: "粥底火鍋", moods: ["健康清淡啲～", "Comfort Food"] }, { name: "避風塘炒蟹", moods: ["想食豪啲！"] }, { name: "脆皮乳鴿", moods: ["Comfort Food", "想食豪啲！"] }, { name: "豉油王炒麵皇", moods: ["Comfort Food", "快靚正"] }, { name: "啫啫雞煲/啫啫排骨煲", moods: ["Comfort Food", "想食豪啲！"] }, { name: "金銀蛋浸時蔬", moods: ["健康清淡啲～"] }, { name: "大排檔風味小炒", moods: ["Comfort Food"] }, { name: "冬瓜盅 (時令)", moods: ["健康清淡啲～", "想食豪啲！"] }, { name: "快靚正碟頭飯 (如：北菇滑雞飯)", moods: ["快靚正"] } ],
        "中式": [ { name: "粵菜酒樓 (例：片皮鴨, 龍蝦伊麵)", moods: ["想食豪啲！", "Comfort Food"] }, { name: "川菜 (例：水煮魚, 毛血旺)", moods: ["Comfort Food", "想食豪啲！"] }, { name: "京滬菜 (例：北京填鴨, 松子魚)", moods: ["想食豪啲！"] }, { name: "客家菜 (例：梅菜扣肉, 鹽焗雞)", moods: ["Comfort Food"] }, { name: "順德菜 (例：魚生, 煎焗魚嘴)", moods: ["健康清淡啲～", "想食豪啲！"] }, { name: "潮州菜 (例：滷水拼盤, 凍蟹)", moods: ["Comfort Food", "想食豪啲！"] }, { name: "盆菜 (節慶/預訂)", moods: ["想食豪啲！", "Comfort Food"] }, { name: "東坡肉", moods: ["Comfort Food", "想食豪啲！"] }, { name: "佛跳牆 (預訂)", moods: ["想食豪啲！"] }, { name: "精緻私房菜", moods: ["想食豪啲！"] }, { name: "中式火鍋 (鴛鴦鍋)", moods: ["想食豪啲！", "Comfort Food"] }, { name: "羊腩煲 (冬季)", moods: ["Comfort Food", "想食豪啲！"] }, { name: "家常便飯套餐 (兩餸一湯)", moods: ["快靚正"] }, { name: "素菜館 (如羅漢齋)", moods: ["健康清淡啲～"] } ],
        "台式": [ { name: "三杯雞套餐", moods: ["Comfort Food", "想食豪啲！"] }, { name: "滷肉飯配小菜套餐", moods: ["Comfort Food", "快靚正"] }, { name: "台式火鍋 (臭臭鍋/沙茶鍋/麻辣鍋)", moods: ["Comfort Food", "想食豪啲！"] }, { name: "薑母鴨 (冬季)", moods: ["Comfort Food", "健康清淡啲～"] }, { name: "鹽酥雞拼盤 (主菜)", moods: ["Comfort Food"] }, { name: "麻油雞麵線", moods: ["Comfort Food", "健康清淡啲～"] }, { name: "鳳梨苦瓜雞湯", moods: ["健康清淡啲～", "Comfort Food"] }, { name: "客家小炒 (台式)", moods: ["Comfort Food"] }, { name: "蔭鼓蚵", moods: ["Comfort Food"] }, { name: "蒼蠅頭", moods: ["Comfort Food"] }, { name: "菜脯蛋", moods: ["Comfort Food", "快靚正"] }, { name: "花雕雞煲", moods: ["Comfort Food", "想食豪啲！"] } ],
        "日式": [ { name: "壽司Omakase", moods: ["想食豪啲！"] }, { name: "鐵板燒套餐", moods: ["想食豪啲！", "Comfort Food"] }, { name: "天婦羅盛合配白飯味噌湯", moods: ["Comfort Food", "想食豪啲！"] }, { name: "鰻魚飯 (鰻重)", moods: ["想食豪啲！", "Comfort Food"] }, { name: "日式火鍋 (Shabu Shabu/Sukiyaki)", moods: ["想食豪啲！", "Comfort Food", "健康清淡啲～"] }, { name: "居酒屋串燒拼盤", moods: ["Comfort Food"] }, { name: "爐端燒", moods: ["想食豪啲！"] }, { name: "懷石料理", moods: ["想食豪啲！", "健康清淡啲～"] }, { name: "壽喜燒 (Sukiyaki) 套餐", moods: ["想食豪啲！", "Comfort Food"] }, { name: "串揚 (Kushikatsu) 盛合", moods: ["Comfort Food"] }, { name: "日式燒肉 (Yakiniku) 自助/套餐", moods: ["想食豪啲！", "Comfort Food"] }, { name: "蟹道樂式蟹宴", moods: ["想食豪啲！"] }, { name: "日式咖喱豬扒飯", moods: ["快靚正", "Comfort Food"] }, { name: "雜錦魚生飯", moods: ["健康清淡啲～", "快靚正"] } ],
        "韓式": [ { name: "韓式烤肉 (KBBQ) 拼盤", moods: ["想食豪啲！", "Comfort Food"] }, { name: "部隊鍋", moods: ["Comfort Food"] }, { name: "人參雞湯", moods: ["健康清淡啲～", "Comfort Food", "想食豪啲！"] }, { name: "海鮮煎餅", moods: ["Comfort Food"] }, { name: "醬油蟹", moods: ["想食豪啲！"] }, { name: "安東雞", moods: ["Comfort Food"] }, { name: "韓式豬蹄 (Jokbal) 配生菜包", moods: ["Comfort Food", "想食豪啲！"] }, { name: "泡菜鍋配白飯", moods: ["Comfort Food"] }, { name: "雪濃湯配飯", moods: ["健康清淡啲～", "Comfort Food"] }, { name: "韓式宮廷料理套餐", moods: ["想食豪啲！", "健康清淡啲～"] }, { name: "辣燉排骨 (Maeun Galbijjim)", moods: ["Comfort Food", "想食豪啲！"] }, { name: "韓式炸雞配啤酒 (Chimaek)", moods: ["Comfort Food", "快靚正"] } ],
        "西式": [ { name: "牛扒 (西冷/肉眼/牛柳)", moods: ["想食豪啲！", "Comfort Food"] }, { name: "烤羊架配薄荷醬", moods: ["想食豪啲！"] }, { name: "烤春雞配香草薯菜", moods: ["Comfort Food", "想食豪啲！"] }, { name: "海鮮意大利飯 (Risotto)", moods: ["想食豪啲！", "Comfort Food"] }, { name: "Fine Dining (多道菜套餐)", moods: ["想食豪啲！"] }, { name: "歐陸菜小館 (例：油封鴨腿)", moods: ["Comfort Food", "想食豪啲！"] }, { name: "烤豬肋骨 (BBQ Ribs)", moods: ["Comfort Food", "想食豪啲！"] }, { name: "威靈頓牛柳", moods: ["想食豪啲！"] }, { name: "法式洋蔥湯配法包", moods: ["Comfort Food", "健康清淡啲～"] }, { name: "龍蝦湯", moods: ["想食豪啲！"] }, { name: "烤鴨胸配橙酒汁", moods: ["想食豪啲！"] }, { name: "海鮮拼盤 (Seafood Platter)", moods: ["想食豪啲！"] }, { name: "漢堡包薯條套餐", moods: ["快靚正", "Comfort Food"] }, { name: "焗三文魚配蘆筍", moods: ["健康清淡啲～"] } ],
        "意大利菜": [ { name: "各式手造意粉 (例：龍蝦意粉)", moods: ["Comfort Food", "想食豪啲！"] }, { name: "柴火烤薄餅 (Pizza)", moods: ["Comfort Food", "快靚正"] }, { name: "意式燴牛仔膝 (Osso Buco)", moods: ["想食豪啲！", "Comfort Food"] }, { name: "千層麵 (Lasagna)", moods: ["Comfort Food"] }, { name: "墨魚汁意粉/飯", moods: ["想食豪啲！"] }, { name: "T骨牛扒 (Bistecca alla Fiorentina)", moods: ["想食豪啲！"] }, { name: "意式雲吞 (Ravioli) 配松露醬", moods: ["Comfort Food", "想食豪啲！"] }, { name: "意式烤羊膝", moods: ["想食豪啲！", "Comfort Food"] }, { name: "松露意大利飯", moods: ["想食豪啲！"] }, { name: "海鮮薄餅", moods: ["快靚正", "想食豪啲！"] }, { name: "意式蔬菜湯 (Minestrone)", moods: ["健康清淡啲～"] } ],
        "東南亞": [ { name: "泰國菜 (例：冬蔭功, 咖喱蟹, 燒豬頸肉)", moods: ["Comfort Food", "想食豪啲！"] }, { name: "越南菜 (例：蔗蝦, 燒牛肉撈檬, 炸春卷)", moods: ["健康清淡啲～", "Comfort Food"] }, { name: "星馬菜 (例：辣椒蟹, 參巴醬燒魚, 海南雞飯)", moods: ["想食豪啲！", "Comfort Food"] }, { name: "印尼菜 (例：巴東牛肉, 印尼炒飯)", moods: ["Comfort Food"] }, { name: "馬來西亞沙嗲串燒拼盤", moods: ["Comfort Food", "快靚正"] }, { name: "泰式生蝦刺身", moods: ["想食豪啲！"] }, { name: "越南牛油雞翼", moods: ["Comfort Food"] }, { name: "泰式明爐蒸魚", moods: ["健康清淡啲～", "想食豪啲！"] }, { name: "新加坡胡椒蟹", moods: ["想食豪啲！"] }, { name: "泰式炒金邊粉 (Pad Thai)", moods: ["快靚正", "Comfort Food"] } ],
        "其他特色": [ { name: "西班牙海鮮飯 (Paella)", moods: ["想食豪啲！", "Comfort Food"] }, { name: "法國菜 (例：油封鴨腿, 法式蝸牛)", moods: ["想食豪啲！"] }, { name: "印度菜 (例：Tandoori烤雞, 咖喱羊肉, 蒜蓉烤餅)", moods: ["Comfort Food", "想食豪啲！"] }, { name: "墨西哥菜 (例：Tacos, Fajitas, Nachos)", moods: ["Comfort Food", "快靚正"] }, { name: "德國菜 (例：鹹豬手配酸菜)", moods: ["Comfort Food", "想食豪啲！"] }, { name: "瑞士芝士火鍋 (Fondue)", moods: ["想食豪啲！", "Comfort Food"] }, { name: "俄羅斯菜 (例：羅宋湯, 俄式牛柳絲)", moods: ["Comfort Food"] }, { name: "巴西烤肉 (Churrascaria)", moods: ["想食豪啲！", "Comfort Food"] }, { name: "中東烤肉拼盤 (Mezze Platter) 配Pita餅", moods: ["Comfort Food", "健康清淡啲～"] }, { name: "秘魯菜 (例：Ceviche, Lomo Saltado)", moods: ["想食豪啲！"] } ]
    },
    supper: {
        "港式": [ { name: "碗仔翅", moods: ["Comfort Food", "快靚正"] }, { name: "魚蛋燒賣 (街邊檔)", moods: ["快靚正", "Comfort Food"] }, { name: "炸大腸", moods: ["Comfort Food"] }, { name: "串燒 (港式雞腎/墨魚丸)", moods: ["Comfort Food", "快靚正"] }, { name: "車仔麵 (宵夜檔)", moods: ["快靚正", "Comfort Food"] }, { name: "潮州打冷 (鵝片、蠔餅)", moods: ["想食豪啲！", "Comfort Food"] }, { name: "炒粉麵 (乾炒牛河、豉油王炒麵)", moods: ["Comfort Food", "快靚正"] }, { name: "即食麵加料 (餐蛋/沙嗲牛)", moods: ["快靚正", "Comfort Food"] }, { name: "煎釀三寶", moods: ["快靚正", "Comfort Food"] }, { name: "生菜魚肉湯", moods: ["健康清淡啲～", "Comfort Food"] }, { name: "豉椒炒蜆", moods: ["Comfort Food", "想食豪啲！"] }, { name: "炸雞脾", moods: ["Comfort Food"] }, { name: "狗仔粉", moods: ["Comfort Food"] }, { name: "艇仔粥", moods: ["Comfort Food", "健康清淡啲～"] } ],
        "中式": [ { name: "皮蛋瘦肉粥/艇仔粥", moods: ["健康清淡啲～", "Comfort Food"] }, { name: "糖水 (芝麻糊、合桃糊、腐竹雞蛋)", moods: ["Comfort Food", "健康清淡啲～"] }, { name: "宵夜點心 (蝦餃、燒賣、鳳爪)", moods: ["Comfort Food", "想食豪啲！"] }, { name: "腸粉 (宵夜檔)", moods: ["快靚正", "Comfort Food"] }, { name: "粢飯豆漿 (宵夜檔)", moods: ["Comfort Food", "快靚正"] }, { name: "雲吞麵 (宵夜)", moods: ["Comfort Food"] }, { name: "糖不甩", moods: ["Comfort Food"] }, { name: "喳咋", moods: ["Comfort Food"] }, { name: "桑寄生蓮子蛋茶", moods: ["健康清淡啲～", "Comfort Food"] }, { name: "麻辣小龍蝦", moods: ["Comfort Food", "想食豪啲！"] } ],
        "台式": [ { name: "鹽酥雞 (宵夜)", moods: ["Comfort Food", "快靚正"] }, { name: "甜不辣 (宵夜)", moods: ["Comfort Food", "快靚正"] }, { name: "大腸麵線 (宵夜)", moods: ["Comfort Food"] }, { name: "滷味拼盤 (台式)", moods: ["Comfort Food", "快靚正"] }, { name: "刈包 (宵夜)", moods: ["Comfort Food"] }, { name: "台式關東煮", moods: ["健康清淡啲～", "Comfort Food"] }, { name: "蚵仔麵線", moods: ["Comfort Food"] }, { name: "台式炸物拼盤 (花枝丸/甜不辣)", moods: ["Comfort Food", "想食豪啲！"] }, { name: "珍珠奶茶 (宵夜)", moods: ["Comfort Food", "快靚正"] }, { name: "藥燉排骨湯", moods: ["健康清淡啲～", "Comfort Food", "想食豪啲！"] } ],
        "日式": [ { name: "居酒屋小食 (串燒、枝豆、炸雞軟骨)", moods: ["Comfort Food", "快靚正"] }, { name: "拉麵 (宵夜份量)", moods: ["Comfort Food", "快靚正"] }, { name: "關東煮", moods: ["健康清淡啲～", "Comfort Food"] }, { name: "日式炒麵 (Yakisoba)", moods: ["Comfort Food"] }, { name: "茶漬飯 (Ochazuke)", moods: ["健康清淡啲～", "Comfort Food"] }, { name: "日式餃子 (宵夜)", moods: ["Comfort Food", "快靚正"] }, { name: "玉子燒", moods: ["Comfort Food", "快靚正"] }, { name: "清酒煮蜆", moods: ["Comfort Food", "想食豪啲！"] }, { name: "串燒盛合", moods: ["想食豪啲！", "Comfort Food"] } ],
        "快餐/輕食": [ { name: "即食麵 (自己煮)", moods: ["快靚正", "Comfort Food"] }, { name: "便利店關東煮/點心", moods: ["快靚正", "健康清淡啲～"] }, { name: "薯片/零食", moods: ["Comfort Food"] }, { name: "杯麵", moods: ["快靚正", "Comfort Food"] }, { name: "麥當勞/KFC (24小時分店)", moods: ["快靚正"] }, { name: "叮叮點心/飯盒", moods: ["快靚正"] }, { name: "芝士撈麵", moods: ["Comfort Food", "快靚正"] }, { name: "烤蕃薯", moods: ["健康清淡啲～", "Comfort Food"] }, { name: "熱狗腸仔", moods: ["快靚正", "Comfort Food"] }, { name: "微波爐爆谷", moods: ["Comfort Food"] }, { name: "雪糕杯", moods: ["想食豪啲！", "Comfort Food"] } ],
        "其他": [ { name: "串燒 (新疆/沙嗲)", moods: ["Comfort Food", "快靚正"] }, { name: "甜品 (B仔涼粉、芒果糯米糍、楊枝甘露)", moods: ["Comfort Food", "想食豪啲！"] }, { name: "台式鹽酥雞", moods: ["Comfort Food"] }, { name: "韓式炸雞 (外賣宵夜)", moods: ["Comfort Food", "想食豪啲！"] }, { name: "滷味 (台式/港式)", moods: ["Comfort Food"] }, { name: "Pizza (外賣)", moods: ["Comfort Food", "想食豪啲！"] }, { name: "臭豆腐", moods: ["Comfort Food"] }, { name: "麻辣燙 (宵夜)", moods: ["Comfort Food"] }, { name: "土匪雞翼", moods: ["Comfort Food"] }, { name: "清湯牛腩蘿蔔", moods: ["健康清淡啲～", "Comfort Food"] } ]
    }
};
