// restaurant_data.js
// 建議將此檔案儲存為 restaurant_data.js 並與主 HTML 檔案放在同一目錄下

const restaurantData = [
    // 港式
    { name: "澳洲牛奶公司", cuisine: "港式", district: ["佐敦"], note: "炒蛋多士, 燉奶", moods: ["快靚正", "Comfort Food"], price: "$" },
    { name: "華嫂冰室", cuisine: "港式", district: ["灣仔", "觀塘", "元朗市中心", "尖沙咀"], note: "菠蘿包, 番茄豬扒通粉", moods: ["快靚正", "Comfort Food"], price: "$" },
    { name: "金鳳茶餐廳", cuisine: "港式", district: ["灣仔"], note: "酥皮蛋撻, 雞批", moods: ["快靚正", "Comfort Food"], price: "$" },
    { name: "九記牛腩", cuisine: "港式", district: ["中環"], note: "清湯牛腩, 咖喱牛筋腩", moods: ["Comfort Food"], price: "$$" },
    { name: "添好運點心專門店", cuisine: "港式", district: ["旺角", "深水埗", "中環", "北角", "將軍澳"], note: "酥皮焗叉燒包", moods: ["快靓正", "Comfort Food"], price: "$$" },
    { name: "大班樓", cuisine: "港式", district: ["中環"], note: "雞油花雕蒸花蟹, 樟茶鴨", moods: ["想食豪啲！"], price: "$$$$" },
    { name: "鏞記酒家", cuisine: "港式", district: ["中環"], note: "燒鵝, 皮蛋酸薑", moods: ["想食豪啲！", "Comfort Food"], price: "$$$" },
    { name: "坤記煲仔小菜", cuisine: "港式", district: ["西環"], note: "臘味煲仔飯, 豉汁白鱔煲仔飯", moods: ["Comfort Food"], price: "$$" },
    { name: "勝香園", cuisine: "港式", district: ["中環"], note: "茄牛通, 檸蜜脆脆", moods: ["快靚正", "Comfort Food"], price: "$" },
    { name: "蘭芳園", cuisine: "港式", district: ["中環", "尖沙咀"], note: "絲襪奶茶, 豬扒包, 蔥油雞扒撈丁", moods: ["快靚正", "Comfort Food"], price: "$" },
    { name: "新香園 (堅記)", cuisine: "港式", district: ["深水埗"], note: "豬手麵, 蛋牛治", moods: ["快靓正", "Comfort Food", "宵夜佳選"], price: "$" },
    { name: "民聲冰室", cuisine: "港式", district: ["大坑"], note: "鹹蛋蒸肉餅, 瑞士雞翼", moods: ["Comfort Food"], price: "$$" },
    { name: "陸羽茶室", cuisine: "港式", district: ["中環"], note: "傳統點心, 杏汁白肺湯", moods: ["想食豪啲！"], price: "$$$" },
    { name: "一點心", cuisine: "港式", district: ["太子", "旺角"], note: "即叫即蒸點心", moods: ["快靚正", "Comfort Food"], price: "$" },
    { name: "蓮香居", cuisine: "港式", district: ["上環"], note: "傳統點心車仔點心, 豬潤燒賣", moods: ["Comfort Food"], price: "$$" },
    { name: "祥興記上海生煎包", cuisine: "港式", district: ["旺角", "尖沙咀", "銅鑼灣"], note: "生煎包", moods: ["快靚正", "Comfort Food"], price: "$" },
    { name: "翠華餐廳", cuisine: "港式", district: ["尖沙咀", "中環", "銅鑼灣", "旺角", "機場"], note: "連鎖茶餐廳, 魚蛋粉, 奶油豬", moods: ["快靚正", "Comfort Food"], price: "$$" },
    { name: "太興", cuisine: "港式", district: ["旺角", "銅鑼灣", "觀塘", "沙田市中心"], note: "燒味, 冰鎮奶茶", moods: ["快靚正", "Comfort Food"], price: "$$" },
    { name: "澳門茶餐廳", cuisine: "港式", district: ["尖沙咀", "銅鑼灣", "上環"], note: "葡撻, 豬扒包, 咖喱牛腩", moods: ["Comfort Food"], price: "$$" },
    { name: "何洪記粥麵專家", cuisine: "港式", district: ["銅鑼灣"], note: "米芝蓮粥麵, 乾炒牛河", moods: ["Comfort Food", "想食豪啲！"], price: "$$$" },
    { name: "一粥麵", cuisine: "港式", district: ["樂富", "黃大仙", "荃灣"], note: "連鎖粥麵店, 套餐", moods: ["快靚正", "健康清淡啲～"], price: "$" },
    { name: "靠得住粥麵小館", cuisine: "港式", district: ["灣仔", "中環", "鰂魚涌"], note: "魚湯粥品, 艇仔粥", moods: ["Comfort Food", "健康清淡啲～"], price: "$$" },
    { name: "佳佳甜品", cuisine: "港式", district: ["佐敦"], note: "中式糖水, 芝麻糊, 合桃糊", moods: ["Comfort Food", "宵夜佳選"], price: "$" },
    { name: "通達食店", cuisine: "港式", district: ["元朗市中心", "旺角", "太子"], note: "街頭小食, 魚蛋, 腸粉", moods: ["快靚正", "Comfort Food"], price: "$" },
    { name: "蛇王芬", cuisine: "港式", district: ["中環"], note: "蛇羹, 臘味飯", moods: ["Comfort Food", "想食豪啲！"], price: "$$$" },
    { name: "星座冰室", cuisine: "港式", district: ["尖沙咀"], note: "番茄麵, 炒蛋", moods: ["Comfort Food", "快靚正"], price: "$" },
    { name: "金華冰廳", cuisine: "港式", district: ["太子"], note: "菠蘿油, 蛋撻", moods: ["Comfort Food", "快靚正"], price: "$" },
    { name: "華星冰室", cuisine: "港式", district: ["灣仔", "旺角", "筲箕灣"], note: "黑松露炒蛋多士, 校長多士", moods: ["Comfort Food", "快靚正"], price: "$" },
    { name: "永華麵家", cuisine: "港式", district: ["灣仔"], note: "竹昇麵, 雲吞麵", moods: ["Comfort Food"], price: "$$" },
    { name: "新記餐廳 (車仔麵)", cuisine: "港式", district: ["銅鑼灣", "尖沙咀"], note: "車仔麵, 瑞士雞翼", moods: ["快靚正", "Comfort Food"], price: "$" },
    { name: "周記點心", cuisine: "港式", district: ["西環"], note: "流沙西多士, 蝦多士", moods: ["Comfort Food"], price: "$" },
    { name: "生記粥品專家", cuisine: "港式", district: ["上環"], note: "魚腩粥, 及第粥", moods: ["Comfort Food", "健康清淡啲～"], price: "$" },
    { name: "麥文記麵家", cuisine: "港式", district: ["佐敦"], note: "全蝦雲吞麵, 豬手撈麵", moods: ["Comfort Food"], price: "$$" },
    { name: "四季煲仔飯", cuisine: "港式", district: ["油麻地"], note: "炭爐煲仔飯", moods: ["Comfort Food"], price: "$" },
    { name: "澳洲牛奶公司 (分店)", cuisine: "港式", district: ["灣仔"], note: "炒蛋多士 (較少人)", moods: ["快靚正", "Comfort Food"], price: "$" },
    { name: "海安咖啡室", cuisine: "港式", district: ["上環"], note: "懷舊冰室, 蔥油雞扒", moods: ["Comfort Food"], price: "$" },
    { name: "瑞記咖啡", cuisine: "港式", district: ["上環"], note: "樽仔奶茶, 蛋牛治", moods: ["快靚正", "Comfort Food"], price: "$" },
    { name: "德如茶餐廳", cuisine: "港式", district: ["灣仔"], note: "家常小菜, 碟頭飯", moods: ["Comfort Food", "快靚正"], price: "$" },
    { name: "祥利飯店", cuisine: "港式", district: ["灣仔"], note: "鑊氣小炒, 碟頭飯", moods: ["Comfort Food"], price: "$$" },

    // 中式
    { name: "詠藜園四川擔擔麵", cuisine: "中式", district: ["黃大仙", "尖沙咀"], note: "擔擔麵, 四川小菜", moods: ["Comfort Food"], price: "$$" },
    { name: "北京樓", cuisine: "中式", district: ["金鐘", "中環", "尖沙咀", "旺角", "太古"], note: "片皮鴨, 京式點心", moods: ["想食豪啲！"], price: "$$$" },
    { name: "美心皇宮", cuisine: "中式", district: ["中環", "金鐘", "銅鑼灣", "旺角", "沙田市中心"], note: "粵式點心, 婚宴酒席", moods: ["Comfort Food", "想食豪啲！"], price: "$$$" },
    { name: "東海薈拉斐特", cuisine: "中式", district: ["尖沙咀", "銅鑼灣"], note: "精緻粵菜, 點心", moods: ["想食豪啲！"], price: "$$$$" },
    { name: "胡同", cuisine: "中式", district: ["尖沙咀"], note: "北方菜, 維港景", moods: ["想食豪啲！"], price: "$$$$" },
    { name: "三希樓", cuisine: "中式", district: ["中環", "銅鑼灣"], note: "川菜, 水煮魚", moods: ["Comfort Food", "想食豪啲！"], price: "$$$" },
    { name: "夜上海", cuisine: "中式", district: ["金鐘", "尖沙咀"], note: "上海菜, 蟹粉菜式", moods: ["想食豪啲！"], price: "$$$$" },
    { name: "好到底麵家", cuisine: "中式", district: ["元朗市中心"], note: "蝦籽撈麵, 雲吞麵", moods: ["Comfort Food"], price: "$" },
    { name: "麥奀雲吞麵世家", cuisine: "中式", district: ["中環", "佐敦", "銅鑼灣"], note: "傳統雲吞麵", moods: ["Comfort Food"], price: "$$" },
    { name: "海底撈火鍋", cuisine: "中式", district: ["油麻地", "銅鑼灣", "旺角"], note: "川式火鍋, 服務周到", moods: ["Comfort Food", "想食豪啲！"], price: "$$$" },
    { name: "龍景軒", cuisine: "中式", district: ["中環"], note: "米芝蓮三星粵菜", moods: ["想食豪啲！"], price: "$$$$" },
    { name: "卅二公館 (Mott 32)", cuisine: "中式", district: ["中環"], note: "摩登中菜, 叉燒", moods: ["想食豪啲！"], price: "$$$$" },
    { name: "利苑酒家", cuisine: "中式", district: ["中環", "灣仔", "旺角", "觀塘"], note: "粵菜, 點心, 燉湯", moods: ["想食豪啲！", "Comfort Food"], price: "$$$" },
    { name: "譽瓏軒", cuisine: "中式", district: ["中環"], note: "高級粵菜 (澳門過江龍)", moods: ["想食豪啲！"], price: "$$$$" },
    { name: "張公館", cuisine: "中式", district: ["銅鑼灣"], note: "創意中菜", moods: ["想食豪啲！"], price: "$$$" },
    { name: "農圃飯店", cuisine: "中式", district: ["銅鑼灣", "中環"], note: "傳統粵菜", moods: ["想食豪啲！", "Comfort Food"], price: "$$$" },
    { name: "書湘門第", cuisine: "中式", district: ["灣仔", "西環"], note: "湖南菜", moods: ["Comfort Food"], price: "$$" },
    { name: "老上海飯店", cuisine: "中式", district: ["灣仔"], note: "傳統上海菜", moods: ["Comfort Food", "想食豪啲！"], price: "$$$" },
    { name: "鄧記 (四川菜)", cuisine: "中式", district: ["灣仔"], note: "正宗川菜", moods: ["Comfort Food", "想食豪啲！"], price: "$$$" },
    { name: "新斗記", cuisine: "中式", district: ["佐敦", "灣仔", "中環"], note: "燒乳豬, 小炒", moods: ["Comfort Food", "想食豪啲！"], price: "$$$" },
    { name: "名人坊高級粵菜", cuisine: "中式", district: ["中環"], note: "米芝蓮粵菜", moods: ["想食豪啲！"], price: "$$$$" },
    { name: "西苑酒家", cuisine: "中式", district: ["銅鑼灣", "太古"], note: "傳統粵菜, 叉燒", moods: ["想食豪啲！", "Comfort Food"], price: "$$$" },
    { name: "國金軒 (Cuisine Cuisine)", cuisine: "中式", district: ["中環", "尖沙咀"], note: "高級粵菜, 維港景", moods: ["想食豪啲！"], price: "$$$$" },
    { name: "天龍軒", cuisine: "中式", district: ["尖沙咀"], note: "米芝蓮二星粵菜, 酒店頂樓", moods: ["想食豪啲！"], price: "$$$$" },
    { name: "一點心 (荃灣分店)", cuisine: "中式", district: ["荃灣"], note: "即叫即蒸點心", moods: ["快靚正", "Comfort Food"], price: "$" },
    { name: "陸陸雞煲火鍋", cuisine: "中式", district: ["旺角", "銅鑼灣"], note: "雞煲, 火鍋", moods: ["Comfort Food", "想食豪啲！"], price: "$$$" },
    { name: "唐閣", cuisine: "中式", district: ["尖沙咀"], note: "米芝蓮三星粵菜", moods: ["想食豪啲！"], price: "$$$$" },
    { name: "福臨門酒家", cuisine: "中式", district: ["灣仔"], note: "富豪飯堂, 傳統粵菜", moods: ["想食豪啲！"], price: "$$$$" },
    { name: "家全七福酒家", cuisine: "中式", district: ["灣仔"], note: "精緻粵菜", moods: ["想食豪啲！"], price: "$$$$" },
    { name: "好彩海鮮酒家", cuisine: "中式", district: ["北角", "旺角"], note: "海鮮, 粵菜", moods: ["Comfort Food", "想食豪啲！"], price: "$$$" },
    { name: "大都烤鴨", cuisine: "中式", district: ["尖沙咀"], note: "北京烤鴨", moods: ["想食豪啲！"], price: "$$$" },
    { name: "王子飯店", cuisine: "中式", district: ["尖沙咀"], note: "京川滬菜", moods: ["想食豪啲！"], price: "$$$" },
    { name: "鴻星海鮮酒家", cuisine: "中式", district: ["灣仔", "觀塘", "旺角"], note: "卡通點心, 海鮮", moods: ["Comfort Food"], price: "$$$" },
    { name: "鳳城酒家", cuisine: "中式", district: ["太子", "北角"], note: "順德菜", moods: ["Comfort Food"], price: "$$" },

    // 台式
    { name: "鼎泰豐", cuisine: "台式", district: ["銅鑼灣", "尖沙咀", "沙田市中心", "旺角"], note: "小籠包, 排骨蛋炒飯", moods: ["Comfort Food", "想食豪啲！"], price: "$$$" },
    { name: "程班長台灣美食", cuisine: "台式", district: ["荔枝角", "九龍灣"], note: "牛肉麵, 滷肉飯", moods: ["Comfort Food", "快靚正"], price: "$$" },
    { name: "阿元來了", cuisine: "台式", district: ["西環", "觀塘"], note: "滷肉飯, 蛋餅, 小食", moods: ["Comfort Food", "快靚正"], price: "$" },
    { name: "叁和院台灣風格飲食", cuisine: "台式", district: ["旺角"], note: "創意台菜, 包點可愛", moods: ["Comfort Food"], price: "$$" },
    { name: "Check In Taipei", cuisine: "台式", district: ["旺角", "尖沙咀", "銅鑼灣"], note: "新派台菜, 珍珠奶茶火鍋", moods: ["Comfort Food"], price: "$$" },
    { name: "吃什麼 What's To Eat", cuisine: "台式", district: ["深水埗", "太子"], note: "台式便當, 小食", moods: ["快靚正", "Comfort Food"], price: "$" },
    { name: "茶木‧台式休閒餐廳", cuisine: "台式", district: ["銅鑼灣", "旺角", "荃灣", "沙田市中心"], note: "台式套餐, 甜品, 珍珠奶茶", moods: ["Comfort Food", "快靚正"], price: "$$" },
    { name: "九份飽", cuisine: "台式", district: ["旺角", "銅鑼灣", "荃灣"], note: "台式麵食, 滷味", moods: ["快靚正", "Comfort Food"], price: "$" },
    { name: "我想和你無所事事", cuisine: "台式", district: ["旺角"], note: "文青風台式餐廳, 輕食", moods: ["Comfort Food", "健康清淡啲～"], price: "$$" },
    { name: "小時光scoool", cuisine: "台式", district: ["長沙灣"], note: "台式家常便飯, 懷舊風格", moods: ["Comfort Food", "健康清淡啲～"], price: "$$" },
    { name: "一起食堂", cuisine: "台式", district: ["太子"], note: "台式便當, 麵線", moods: ["快靚正", "Comfort Food"], price: "$" },
    { name: "幸福週末", cuisine: "台式", district: ["銅鑼灣"], note: "台式厚多士, 飲品", moods: ["Comfort Food"], price: "$$" },
    { name: "天仁茗茶 (喫茶趣)", cuisine: "台式", district: ["銅鑼灣", "金鐘", "旺角"], note: "茶料理, 珍珠奶茶", moods: ["健康清淡啲～", "Comfort Food"], price: "$$" },
    { name: "龍鳳號", cuisine: "台式", district: ["灣仔"], note: "滷肉飯, 刈包", moods: ["Comfort Food", "快靚正"], price: "$" },
    { name: "請坐 (Seat Please)", cuisine: "台式", district: ["旺角", "尖沙咀"], note: "台式料理, 芋圓", moods: ["Comfort Food"], price: "$$" },
    { name: "老媽拌麵 (香港店)", cuisine: "台式", district: ["中環", "銅鑼灣"], note: "即食拌麵, 堂食套餐", moods: ["快靚正", "Comfort Food"], price: "$$" },
    { name: "圓圓 (Yuan Is Here)", cuisine: "台式", district: ["西環", "旺角"], note: "滷肉飯, 鹽酥雞", moods: ["Comfort Food", "快靚正"], price: "$" },
    { name: "燈籠滷味", cuisine: "台式", district: ["旺角"], note: "台式滷味", moods: ["Comfort Food", "快靚正"], price: "$" },
    { name: "老虎堂黑糖專売", cuisine: "台式", district: ["多區"], note: "黑糖珍珠鮮奶", moods: ["Comfort Food"], price: "$" },
    { name: "幸福堂", cuisine: "台式", district: ["多區"], note: "手炒黑糖珍珠鮮奶", moods: ["Comfort Food"], price: "$" },
    { name: "艋舺雞排", cuisine: "台式", district: ["旺角"], note: "台式炸雞排", moods: ["Comfort Food", "快靚正"], price: "$" },
    { name: "度小月擔仔麵", cuisine: "台式", district: ["銅鑼灣"], note: "擔仔麵, 滷肉飯", moods: ["Comfort Food"], price: "$$" },
    { name: "春水堂", cuisine: "台式", district: ["觀塘", "尖沙咀"], note: "珍珠奶茶始祖, 台式餐點", moods: ["Comfort Food"], price: "$$" },
    { name: "永康牛肉麵 (香港店)", cuisine: "台式", district: ["銅鑼灣"], note: "紅燒牛肉麵", moods: ["Comfort Food", "想食豪啲！"], price: "$$$" },
    { name: "阿甘麵館", cuisine: "台式", district: ["北角"], note: "台式麵食, 小菜", moods: ["Comfort Food", "快靚正"], price: "$" },

    // 日式 (Continue adding to reach target)
    { name: "一蘭拉麵", cuisine: "日式", district: ["銅鑼灣", "尖沙咀", "旺角"], note: "豚骨拉麵", moods: ["Comfort Food", "快靚正"], price: "$$" },
    { name: "壽司郎", cuisine: "日式", district: ["佐敦", "黃埔花園", "荔枝角", "旺角", "多區"], note: "迴轉壽司", moods: ["快靚正", "Comfort Food"], price: "$" },
    { name: "和民居食屋", cuisine: "日式", district: ["銅鑼灣", "旺角", "荃灣", "多區"], note: "綜合日式料理", moods: ["Comfort Food", "快靚正"], price: "$$" },
    { name: "俺流塩らーめん", cuisine: "日式", district: ["銅鑼灣", "尖沙咀", "中環"], note: "鹽味拉麵, 沾麵", moods: ["Comfort Food"], price: "$$" },
    { name: "Sushi Saito", cuisine: "日式", district: ["中環"], note: "頂級Omakase", moods: ["想食豪啲！"], price: "$$$$" },
    { name: "Yardbird", cuisine: "日式", district: ["上環"], note: "日式串燒 (雞肉專門)", moods: ["Comfort Food", "想食豪啲！"], price: "$$$" },
    { name: "Zuma", cuisine: "日式", district: ["中環"], note: "現代日式料理, 早午餐", moods: ["想食豪啲！"], price: "$$$$" },
    { name: "豚王", cuisine: "日式", district: ["中環", "銅鑼灣", "尖沙咀", "沙田市中心"], note: "豚骨拉麵, 限定王", moods: ["Comfort Food"], price: "$$" },
    { name: "丸龜製麵", cuisine: "日式", district: ["中環", "旺角", "觀塘", "多區"], note: "自助烏冬, 天婦羅", moods: ["快靚正", "健康清淡啲～"], price: "$" },
    { name: "牛角日本燒肉專門店", cuisine: "日式", district: ["銅鑼灣", "旺角", "尖沙咀", "多區"], note: "日式燒肉放題/套餐", moods: ["Comfort Food", "想食豪啲！"], price: "$$$" },
    { name: "AFURI 辛紅", cuisine: "日式", district: ["銅鑼灣", "尖沙咀"], note: "柚子鹽拉麵, 辣味拉麵", moods: ["Comfort Food"], price: "$$" },
    { name: "權八居酒屋 (Gonpachi)", cuisine: "日式", district: ["銅鑼灣"], note: "串燒, 蕎麥麵, 電影Kill Bill場景", moods: ["想食豪啲！", "Comfort Food"], price: "$$$" },
    { name: "Sushiyoshi 壽司芳", cuisine: "日式", district: ["尖沙咀"], note: "Omakase, 創意壽司", moods: ["想食豪啲！"], price: "$$$$" },
    { name: "Monster Sushi", cuisine: "日式", district: ["旺角", "尖沙咀", "銅鑼灣"], note: "創意卷物, 刺身", moods: ["Comfort Food"], price: "$$" },
    { name: "金田長壽司", cuisine: "日式", district: ["尖沙咀"], note: "Omakase, 熟客多", moods: ["想食豪啲！"], price: "$$$$" },
    { name: "竹壽司 (Sushi Takeda)", cuisine: "日式", district: ["中環"], note: "Omakase", moods: ["想食豪啲！"], price: "$$$$" },
    { name: "一門 (Ichimon)", cuisine: "日式", district: ["尖沙咀"], note: "拉麵, 沾麵", moods: ["Comfort Food"], price: "$$" },
    { name: "銀座いわ (Ginza Iwa)", cuisine: "日式", district: ["中環"], note: "米芝蓮壽司", moods: ["想食豪啲！"], price: "$$$$" },
    { name: "天海 (Tenkai)", cuisine: "日式", district: ["尖沙咀"], note: "天婦羅Omakase", moods: ["想食豪啲！"], price: "$$$$" },
    { name: "漁獲浜燒 (Uo-Show Hamayaki)", cuisine: "日式", district: ["銅鑼灣"], note: "浜燒海鮮", moods: ["Comfort Food", "想食豪啲！"], price: "$$$" },
    { name: "富士山55沾麵屋", cuisine: "日式", district: ["銅鑼灣", "旺角"], note: "沾麵專門店", moods: ["Comfort Food"], price: "$$" },
    { name: "三田製麵所", cuisine: "日式", district: ["銅鑼灣", "尖沙咀", "旺角"], note: "濃厚豚骨魚介沾麵", moods: ["Comfort Food"], price: "$$" },
    { name: "吉豚屋吉列豬扒專門店 (Katsuya)", cuisine: "日式", district: ["銅鑼灣", "旺角", "多區"], note: "吉列豬扒飯", moods: ["Comfort Food", "快靚正"], price: "$" },
    { name: "鳥華亭 (Torihana Tei)", cuisine: "日式", district: ["銅鑼灣", "中環"], note: "親子丼, 雞肉料理", moods: ["Comfort Food"], price: "$$$" },
    { name: "鮨魯山", cuisine: "日式", district: ["灣仔"], note: "Omakase", moods: ["想食豪啲！"], price: "$$$$" },
    { name: "八兵衛 (Hachibei)", cuisine: "日式", district: ["中環"], note: "博多串燒", moods: ["想食豪啲！", "Comfort Food"], price: "$$$" },
    { name: "穴藏 (Ana Gura)", cuisine: "日式", district: ["中環"], note: "Omakase, 隱世小店", moods: ["想食豪啲！"], price: "$$$$" },
    { name: "拉麵Jo (Ramen Jo)", cuisine: "日式", district: ["銅鑼灣"], note: "橫濱家系拉麵", moods: ["Comfort Food"], price: "$$" },
    { name: "Sake Central", cuisine: "日式", district: ["中環"], note: "清酒吧, 佐酒小食", moods: ["想食豪啲！"], price: "$$$" },
    { name: "UMI", cuisine: "日式", district: ["中環"], note: "Omakase", moods: ["想食豪啲！"], price: "$$$$" },
    { name: "Nadai Unatoto (名代宇奈とと)", cuisine: "日式", district: ["尖沙咀", "銅鑼灣"], note: "平價鰻魚飯", moods: ["快靚正", "Comfort Food"], price: "$" },
    { name: "金子半之助", cuisine: "日式", district: ["葵芳", "九龍灣"], note: "江戶前天丼", moods: ["Comfort Food"], price: "$$" },
    { name: "一幻拉麵", cuisine: "日式", district: ["中環", "尖沙咀"], note: "蝦湯拉麵", moods: ["Comfort Food"], price: "$$" },
    { name: "鮨見 (Sushi Gin)", cuisine: "日式", district: ["銅鑼灣"], note: "Omakase", moods: ["想食豪啲！"], price: "$$$$" },
    { name: "東京築地食堂", cuisine: "日式", district: ["太古"], note: "魚生飯, 壽司", moods: ["Comfort Food"], price: "$$" },

    // 韓式 (Continued)
    { name: "O'taste", cuisine: "韓式", district: ["銅鑼灣"], note: "韓式小食, 炸雞", moods: ["快靚正", "Comfort Food"], price: "$" },
    { name: "Mr. Korea BBQ", cuisine: "韓式", district: ["旺角"], note: "韓燒", moods: ["Comfort Food", "想食豪啲！"], price: "$$$" },
    { name: "Seoul Recipe", cuisine: "韓式", district: ["中環", "金鐘"], note: "韓式外賣, 飯卷", moods: ["快靚正", "健康清淡啲～"], price: "$$" },
    { name: "江南韓國料理 (Gangnam)", cuisine: "韓式", district: ["銅鑼灣"], note: "傳統韓菜", moods: ["Comfort Food"], price: "$$$" },
    { name: "BBQ 7080", cuisine: "韓式", district: ["旺角", "尖沙咀"], note: "懷舊韓燒", moods: ["Comfort Food"], price: "$$" },

    // 西式/意大利菜 (Continued)
    { name: "BLT Steak", cuisine: "西式", district: ["尖沙咀"], note: "美式扒房", moods: ["想食豪啲！"], price: "$$$$" },
    { name: "Jamie's Italian", cuisine: "意大利菜", district: ["銅鑼灣", "尖沙咀"], note: "Jamie Oliver 意菜", moods: ["Comfort Food"], price: "$$$" },
    { name: "The Butchers Club Burger", cuisine: "西式", district: ["灣仔", "中環"], note: "乾式熟成牛肉漢堡", moods: ["Comfort Food", "想食豪啲！"], price: "$$$" },
    { name: "Pirata", cuisine: "意大利菜", district: ["灣仔"], note: "意大利菜, 早午餐", moods: ["Comfort Food", "想食豪啲！"], price: "$$$" },
    { name: "Linguini Fini", cuisine: "意大利菜", district: ["中環"], note: "手造意粉, 薄餅", moods: ["Comfort Food"], price: "$$$" },
    { name: "LMO Freshly Baked by Richard Ekkebus", cuisine: "西式", district: ["中環"], note: "高級麵包糕點 (Amber旗下)", moods: ["想食豪啲！"], price: "$$$" },
    { name: "Popinjays", cuisine: "西式", district: ["中環"], note: "天台餐廳酒吧, 歐陸菜", moods: ["想食豪啲！"], price: "$$$$" },
    { name: "The Chinnery", cuisine: "西式", district: ["中環"], note: "傳統英式菜, 文華東方酒店", moods: ["想食豪啲！", "Comfort Food"], price: "$$$$" },
    { name: "LucAle", cuisine: "意大利菜", district: ["西環"], note: "意式小館, 手造意粉", moods: ["Comfort Food", "想食豪啲！"], price: "$$$" },
    { name: "Associazione Chianti", cuisine: "意大利菜", district: ["灣仔"], note: "托斯卡納扒房", moods: ["想食豪啲！", "Comfort Food"], price: "$$$$" },
    { name: "Frank's Italian American", cuisine: "意大利菜", district: ["中環"], note: "美式意大利菜 (Fini's 姊妹店)", moods: ["Comfort Food"], price: "$$$" },
    { name: "The Peak Lookout", cuisine: "西式", district: ["山頂"], note: "國際美食, 山頂景色", moods: ["想食豪啲！"], price: "$$$" },
    { name: "Spasso", cuisine: "意大利菜", district: ["尖沙咀"], note: "意大利菜, 維港景", moods: ["想食豪啲！", "Comfort Food"], price: "$$$" },
    { name: "NOM - Not Only Meatballs", cuisine: "意大利菜", district: ["中環"], note: "肉丸, 意大利家常菜", moods: ["Comfort Food"], price: "$$$" },
    { name: "The Verandah", cuisine: "西式", district: ["淺水灣"], note: "殖民地風格餐廳, 自助餐/下午茶", moods: ["想食豪啲！"], price: "$$$$" },

    // 東南亞 (Continued)
    { name: "金不換泰國餐廳", cuisine: "東南亞", district: ["九龍城"], note: "地道泰國菜", moods: ["Comfort Food"], price: "$$" },
    { name: "泰屋 (Thai Basil)", cuisine: "東南亞", district: ["金鐘"], note: "精緻泰國菜", moods: ["想食豪啲！"], price: "$$$" },
    { name: "Chôm Chôm", cuisine: "東南亞", district: ["中環"], note: "越南街頭小食", moods: ["Comfort Food"], price: "$$$" },
    { name: "Pho Bar", cuisine: "東南亞", district: ["中環"], note: "越南牛肉粉", moods: ["Comfort Food", "快靚正"], price: "$$" },
    { name: "Ruam", cuisine: "東南亞", district: ["灣仔"], note: "泰國酒吧餐廳", moods: ["Comfort Food"], price: "$$$" },
    { name: "Sip Song", cuisine: "東南亞", district: ["淺水灣"], note: "泰國海邊餐廳", moods: ["Comfort Food", "想食豪啲！"], price: "$$$" },
    { name: "Cococabana", cuisine: "東南亞", district: ["深水灣"], note: "地中海/亞洲Fusion (但有時被歸類東南亞風情)", moods: ["想食豪啲！"], price: "$$$$" },
    { name: "Aaharn", cuisine: "東南亞", district: ["中環"], note: "高級泰國菜 (David Thompson)", moods: ["想食豪啲！"], price: "$$$$" },
    { name: "Mekong Vietnamese Restaurant", cuisine: "東南亞", district: ["愉景灣"], note: "越南菜", moods: ["Comfort Food"], price: "$$" },
    { name: "Papparich", cuisine: "東南亞", district: ["銅鑼灣", "將軍澳"], note: "馬來西亞連鎖餐廳", moods: ["Comfort Food", "快靚正"], price: "$$" },
    { name: "小曼谷泰國菜館", cuisine: "東南亞", district: ["九龍城"], note: "人氣泰國菜", moods: ["Comfort Food"], price: "$$" },
    { name: "越男仔", cuisine: "東南亞", district: ["旺角", "銅鑼灣"], note: "越南湯粉", moods: ["Comfort Food", "快靚正"], price: "$" },

    // 快餐/輕食 (Continued)
    { name: "Triple O's by White Spot", cuisine: "快餐/輕食", district: ["金鐘", "中環"], note: "加拿大漢堡, 奶昔", moods: ["Comfort Food", "快靚正"], price: "$$" },
    { name: "Pret A Manger", cuisine: "快餐/輕食", district: ["多區"], note: "三文治, 沙律", moods: ["快靚正", "健康清淡啲～"], price: "$$" },
    { name: "BEP Express", cuisine: "快餐/輕食", district: ["中環"], note: "越南快餐, 撈檬", moods: ["快靚正", "健康清淡啲～"], price: "$" },
    { name: "KALE", cuisine: "快餐/輕食", district: ["中環", "灣仔"], note: "健康沙律, 卷餅", moods: ["健康清淡啲～", "快靚正"], price: "$$" },

    // 其他特色 (Continued)
    { name: "The Pontiac", cuisine: "其他特色", district: ["中環"], note: "美式酒吧, 雞尾酒", moods: ["Comfort Food"], price: "$$$" },
    { name: "Shady Acres", cuisine: "其他特色", district: ["中環"], note: "葡萄酒吧, 小食", moods: ["Comfort Food"], price: "$$$" },
    { name: "Honbo", cuisine: "其他特色", district: ["灣仔", "中環"], note: "美式漢堡", moods: ["Comfort Food"], price: "$$" },
    { name: "Teakha 茶。家", cuisine: "其他特色", district: ["上環"], note: "茶館, 輕食, 蛋糕", moods: ["健康清淡啲～", "Comfort Food"], price: "$$" },
    { name: "The Old Man", cuisine: "其他特色", district: ["中環"], note: "亞洲最佳酒吧之一 (海明威主題)", moods: ["想食豪啲！"], price: "$$$" },
    { name: "COBO House", cuisine: "其他特色", district: ["尖沙咀"], note: "藝術 X 餐飲, 亞洲菜", moods: ["想食豪啲！"], price: "$$$$" },
    { name: "Duddell's 都爹利會館", cuisine: "其他特色", district: ["中環"], note: "米芝蓮粵菜, 藝術空間", moods: ["想食豪啲！"], price: "$$$$" },
    { name: "Little Creatures", cuisine: "其他特色", district: ["堅尼地城"], note: "澳洲手工啤酒廠, 西式小食", moods: ["Comfort Food"], price: "$$$" },
    { name: "Second Draft", cuisine: "其他特色", district: ["大坑"], note: "本地手工啤酒, 亞洲風味小食", moods: ["Comfort Food"], price: "$$$" },
    { name: "The Diplomat", cuisine: "其他特色", district: ["中環"], note: "雞尾酒吧, 小食", moods: ["想食豪啲！"], price: "$$$" },
    { name: "Penicillin", cuisine: "其他特色", district: ["中環"], note: "環保概念酒吧, 小食", moods: ["想食豪啲！"], price: "$$$" },
    { name: "Shari Shari Kakigori House 氷屋", cuisine: "其他特色", district: ["銅鑼灣", "中環"], note: "日式刨冰", moods: ["Comfort Food"], price: "$$" },
    { name: "Elephant Grounds", cuisine: "其他特色", district: ["中環", "灣仔", "銅鑼灣", "尖沙咀"], note: "咖啡店, 雪糕三文治, 輕食", moods: ["Comfort Food", "健康清淡啲～"], price: "$$" },
    { name: "NOC Coffee Co.", cuisine: "其他特色", district: ["中環", "西環", "灣仔", "多區"], note: "精品咖啡, 輕食", moods: ["健康清淡啲～", "快靚正"], price: "$$" }
];
